# Álgebra Linear na prática

Para a parte de Álgebra Linear usaremos principalmente dois pacotes do Python: (i) Numpy e (ii) Scikit Learn. O Numpy será muito usado para implementar os conceitos mais fundamentais de Álgebra Linear. Para verificar os comandos do Numpy associados à Álgebra Linear, acessar: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html. 

## Criando vetores e matrizes no Python

Para criar vetores e matrizes no Python basta criar listas e depois convertê-las para Numpy Arrays:

In [ ]:
import numpy as np

Vetores:

In [ ]:
#Criando lista
x=[1,4,2,9]
print(type(x))

#Convertendo
x=np.array(x)
print(type(x)) #já temos um vetor criado

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#Printando Vetor
print(x)

[1 4 2 9]


In [ ]:
#Verificando o "shape"
print(x.shape) #O vetor "x" tem tamanho 4

(4,)


In [ ]:
print(type(np.r_[1,2,3]))

<class 'numpy.ndarray'>


Matrizes:

In [ ]:
#Para criar matrizes é necessário criar listas dentro da lista principal,
#sendo que cada lista interna representa uma linha da matriz.

#Criando lista
A=[[1,4,2],[6,2,8],[3,7,7],[3,4,2]]
print(type(A))

#Convertendo
A=np.array(A)
print(type(A)) #já temos um vetor criado

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#Printando Matriz
print(A)

[[1 4 2]
 [6 2 8]
 [3 7 7]
 [3 4 2]]


In [ ]:
#Verificando o "shape"
print(A.shape) #"A" tem 4 linhas e 3 colunas

(4, 3)


Selecionando colunas e linhas específicas da matriz A:

In [ ]:
print(A[0,:])

[1 4 2]


In [ ]:
print(A[:,2])

[2 8 7 2]


In [ ]:
print(A[:2,1:])

[[4 2]
 [2 8]]


Criando alguns vetores e matrizes específicos:

In [ ]:
x = np.ones(3)  #vetor somente composto de "uns"
y = np.zeros(3) #vetor somente composto de "zeros"

print(x)
print(y)

[1. 1. 1.]
[0. 0. 0.]


In [ ]:
A = np.ones((2,3))  #matriz (2x3) somente composto de "uns"
B = np.zeros((2,3)) #matriz (2x3) somente composto de "zeros"

print(A)
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


## Operações com matrizes e vetores

Soma e subtração:

In [ ]:
x=np.array([1,4,2,9])
y=np.array([2,1,3,0])

print(x+y)
print(x-y)

[3 5 5 9]
[-1  3 -1  9]


Produto por um escalar $\alpha$:

In [ ]:
x=np.array([1,4,2,9])
alpha=2

print(x)
print(alpha*x)

[1 4 2 9]
[ 2  8  4 18]


Transposição:

In [ ]:
A=np.array([[1,4,2],[6,2,8]])
print(A)

[[1 4 2]
 [6 2 8]]


In [ ]:
print(A.T) #transposta: colocar ".T" no fim

[[1 6]
 [4 2]
 [2 8]]


Produto de matrizes:

In [ ]:
A=np.array([[1,4,2],[6,2,8]])
B=np.array([[3,7,7],[3,4,2]])

In [ ]:
#vai dar erro, pois as ordens das matrizes não são compatíveis
C=np.matmul(A,B)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
#usando a transposta de B (B.T)
C=np.matmul(A,B.T)
print(C)

[[45 23]
 [88 42]]


In [ ]:
#Outra maneira
C=A.dot(B.T)
print(C)

[[45 23]
 [88 42]]


Produto elemento a elemento (_element wise product_)

In [ ]:
x=np.array([1,4,2,9])
y=np.array([2,1,3,0])

print(x*y)

[2 4 6 0]


### Exercício 1:

Crie uma função que retorne a norma euclidiana de um vetor **x** usando um loop e nenhuma multiplicação de matrizes. Sua função deve dizer ao usuário se ele não introduzir um outro objeto que não um vetor na hora de usar sua função.

In [ ]:
# escreva seu código aqui

### Exercício 2:

Crie uma função que retorne a norma euclidiana de um vetor **x** usando nenhum loop e uma multiplicação de matrizes. Sua função deve dizer ao usuário se ele não introduzir um outro objeto que não um vetor na hora de usar sua função.

In [ ]:
# escreva seu código aqui

## Produto Escalar e Norma Euclidiana

Ao contrário do que foi feito por você nos exercícios anteriores, usaremos comandos do Numpy para calcular o que precisamos.

In [ ]:
x=np.array([1,4,2,9])
y=np.array([2,1,3,0])

Diferentes maneira de se calcular o produto escalar:

In [ ]:
#Maneira 1
n=x.shape[0]
p=0
for i in range(n):
    p=p+x[i]*y[i]
print("Produto 1="+str(p))

#Maneira 2
p=sum(x*y)
print("Produto 2="+str(p))

#Maneira 3
p=np.matmul(x,y)
print("Produto 3="+str(p))

#Maneira 4
p=np.inner(x,y)
print("Produto 4="+str(p))

Produto 1=12
Produto 2=12
Produto 3=12
Produto 4=12


Norma euclidiana (comparar com a função feita por você):

In [ ]:
np.linalg.norm(x)   

10.099504938362077

## Distâncias entre vetores

In [ ]:
x=np.array([1,4,2,9])
y=np.array([2,1,3,0])

Distância Euclidiana:

In [ ]:
#Para calcular a distância eudlidiana entre dois vetores 
#basta calcular a norma euclidiana da diferença desses vetores

def dist_euclid(a,b):
    return np.linalg.norm(a-b)  

print(dist_euclid(x,y))

9.591663046625438


### Exercício 3:

Crie uma função que retorne ou a Distância Manhatann ou Distância Euclidiana entre dois vetores, dependendo da opção do usuário da sua função.

Distância de Mahalanobis:

In [ ]:
#Iserindo uma base de dados
#As linhas são indivíduos e as colunas são variáveis

data=np.array([[2,3,1],[5,3,1],[4,2,6],[3,5,7],[2,7,3]])
print(data)

[[2 3 1]
 [5 3 1]
 [4 2 6]
 [3 5 7]
 [2 7 3]]


In [ ]:
#Calculando a matriz de Covariância entre as variáveis
#Perceba que a matriz é simétrica
Cov=np.cov(data.T)
print(Cov)

[[ 1.7 -1.5  0.1]
 [-1.5  4.   0.5]
 [ 0.1  0.5  7.8]]


In [ ]:
#Invertendo a matriz de covariância
Inv_cov=np.linalg.inv(Cov)

#Perceba que chegamos à matriz identidade
print(np.matmul(Cov,Inv_cov))

[[ 1.00000000e+00 -1.69135539e-17  5.20417043e-18]
 [-2.63677968e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.77555756e-17  1.00000000e+00]]


In [ ]:
#Calculando a distância do indivíduo 1 ou 2
d=data[1,:].dot(Inv_cov).dot(data[1,:].T)
d=d**(1/2)

print("Euclidiana="+str(dist_euclid(data[1,:],data[2,:]))+", Mahalanobis="+str(d))

Euclidiana=5.196152422706632, Mahalanobis=5.944908366314066


### Exercício 4:

Use a base de dados criada (data) e crie uma função que retorne uma matriz de distâncias euclidianas - essa matriz de distâncias deve ser quadrada e a entrada _(i,j)_ deve conter a distância do indivíduo _i_ ao indivíduo _j_. Perceba que a matriz deve ser simétrica e sua diagonal principal deve ser nula. **Dica**: evite usar loops e tente apenas usar multiplicações de matrizes.

In [ ]:
# escreva seu código aqui

### Exercício 5:

Use a base de dados criada (data) e crie uma função que retorne uma matriz de distâncias de Mahalanobis - essa matriz de distâncias deve ser quadrada e a entrada _(i,j)_ deve conter a distância do indivíduo _i_ ao indivíduo _j_. Perceba que a matriz deve ser simétrica e sua diagonal principal deve ser nula. **Dica**: evite usar loops e tente apenas usar multiplicações de matrizes.

In [ ]:
# escreva seu código aqui